'use strict';
const defaults={orders:10000,activation:85,arpu:200,'service-cost':60,cac:85,hardware:0,retention:75};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const compact=n=>Math.abs(n)>=1e6?'$'+(n/1e6).toFixed(2)+'M':money(n);
function calculateModel(v){const a=v.activation/100,r=v.retention/100,unit=v.arpu-v['service-cost'],paid=v.orders*a,arr=paid*v.arpu;const annualContribution=a*unit;return {paid,arr,margin:v.arpu>0?unit/v.arpu*100:null,contribution:v.orders*(v.hardware-v.cac+annualContribution),ltv:v.hardware-v.cac+annualContribution*(1+r+r*r),payback:annualContribution>0?Math.max(0,v.cac-v.hardware)/(annualContribution/12):null,revenues:[arr,arr*r,arr*r*r]};}
function updateModel(){const v={};for(const id of Object.keys(defaults)){const el=document.getElementById(id);if(!el.checkValidity()||el.value.trim()===''){document.getElementById('model-error').textContent='Enter a value within the displayed field limits. Results retain the last valid scenario.';return;}v[id]=Number(el.value);}document.getElementById('model-error').textContent='';const m=calculateModel(v);document.getElementById('arr').textContent=compact(m.arr);document.getElementById('active-subs').textContent=Math.round(m.paid).toLocaleString();document.getElementById('margin').textContent=m.margin===null?'Not defined':m.margin.toFixed(1)+'%';document.getElementById('contribution').textContent=money(m.contribution);document.getElementById('ltv').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(m.ltv);document.getElementById('payback').textContent=m.payback===null?'No service payback':m.payback.toFixed(1)+' months';m.revenues.forEach((n,i)=>{document.getElementById('rev'+(i+1)).textContent=compact(n);document.getElementById('bar'+(i+1)).style.width=(m.arr>0?n/m.arr*55:0)+'%';});}
const form=document.getElementById('model-form');form.addEventListener('input',updateModel);form.addEventListener('submit',e=>e.preventDefault());document.getElementById('reset-model').addEventListener('click',()=>{for(const [id,v] of Object.entries(defaults))document.getElementById(id).value=v;updateModel();});updateModel();
const items=window.CREATIVE_LIBRARY||[];let shown=20;const gallery=document.getElementById('gallery');const dialog=document.getElementById('asset-dialog');let previousFocus=null;let selected=null;
function filteredItems(){return items.filter(x=>(!document.getElementById('product-filter').value||x.product===document.getElementById('product-filter').value)&&(!document.getElementById('territory-filter').value||x.territory===document.getElementById('territory-filter').value)&&(!document.getElementById('ratio-filter').value||x.ratio===document.getElementById('ratio-filter').value));}
function renderGallery(){const filtered=filteredItems();gallery.replaceChildren();for(const item of filtered.slice(0,shown)){const card=document.createElement('button');card.className='asset-card';card.type='button';card.setAttribute('aria-label','Preview '+item.id+': '+item.title+' — '+item.product);const img=document.createElement('img');img.src='assets/'+item.id+'.webp';img.alt=item.product+' creative concept: '+item.title;img.loading='lazy';img.width=800;img.height=1000;const number=document.createElement('span');number.className='asset-number';number.textContent=item.id;const meta=document.createElement('span');meta.className='asset-meta';const territory=document.createElement('span');territory.textContent=item.territory;const ratio=document.createElement('span');ratio.textContent=item.ratio;meta.append(territory,ratio);const title=document.createElement('h3');title.textContent=item.headline;const product=document.createElement('p');product.textContent=item.product;card.append(img,number,meta,title,product);card.addEventListener('click',()=>openAsset(item,card));gallery.append(card);}document.getElementById('gallery-count').textContent=filtered.length+' concepts · '+Math.min(shown,filtered.length)+' shown';document.getElementById('load-more').hidden=shown>=filtered.length;document.getElementById('load-more').style.display=shown>=filtered.length?'none':'flex';document.getElementById('gallery-empty').hidden=filtered.length>0;}
function openAsset(item,card){selected=item;previousFocus=card;document.getElementById('asset-image').src='assets/'+item.id+'.webp';document.getElementById('asset-image').alt=item.product+' — '+item.title;document.getElementById('asset-id').textContent=item.id+' / '+item.territory+' / '+item.ratio;document.getElementById('asset-title').textContent=item.title;document.getElementById('asset-product').textContent=item.product;document.getElementById('asset-headline').textContent=item.headline;document.getElementById('asset-scene').textContent=item.scene+'.';document.getElementById('asset-original').href=item.url;document.getElementById('copy-status').textContent='';dialog.showModal();document.getElementById('close-dialog').focus();}
for(const id of ['product-filter','territory-filter','ratio-filter'])document.getElementById(id).addEventListener('change',()=>{shown=20;renderGallery();});document.getElementById('load-more').addEventListener('click',()=>{shown+=20;renderGallery();});document.getElementById('close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{if(previousFocus)previousFocus.focus();});document.getElementById('copy-headline').addEventListener('click',async()=>{if(!selected)return;try{await navigator.clipboard.writeText(selected.headline);document.getElementById('copy-status').textContent='Headline copied.';}catch{document.getElementById('copy-status').textContent='Copy is unavailable in this browser. Select the headline above to copy it.';}});renderGallery();
